[package]
name = "tokio-dbus"
version = "0.1.0"
authors = ["Michael Smith <michael@spinda.net>"]

[dependencies]
futures = "0.1.10"
libc = "0.2.17"
nom = "2.1.0"
tokio-core = "0.1.4"
tokio-uds = "0.1.2"
